-- Postgres Schema for Black and White Chef Trends Data
-- Targeted for Supabase

-- Option 1: Unified Table (Recommended for analysis)
-- This normalizes the data so all chefs and sources are in one place.

CREATE TABLE IF NOT EXISTS chef_trends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    chef_name VARCHAR(100) NOT NULL,
    source VARCHAR(50) NOT NULL CHECK (source IN ('google', 'naver')), -- 'google' or 'naver'
    score DECIMAL(10, 5) NOT NULL, -- Handles both float (Naver) and int/float (Google)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Indexes for fast querying
CREATE INDEX idx_chef_trends_date ON chef_trends(date);
CREATE INDEX idx_chef_trends_chef_name ON chef_trends(chef_name);
CREATE INDEX idx_chef_trends_source ON chef_trends(source);

-- Unique constraint to prevent duplicates (optional but good for idempotency)
ALTER TABLE chef_trends ADD CONSTRAINT unique_trend_entry UNIQUE (date, chef_name, source);

COMMENT ON TABLE chef_trends IS 'Stores daily search trend data from Google and Naver for chefs';
COMMENT ON COLUMN chef_trends.score IS 'Normalized search volume/ratio. Naver is usually 0-100 float, Google is 0-100 int/float.';
